##################################################
#### REMOVENDO USUARIOS, PRODUTOS E CARRINHOS
##################################################

#### Rota para deletar usuarios pelo id
DELETE http://127.0.0.1:8000/usuarios/1 HTTP/1.1
content-type: application/json


####################################################
#### Rota para deletar produto pelo id
DELETE http://127.0.0.1:8000/produtos/2 HTTP/1.1
content-type: application/json


###################################################
##### Rota para remover produto do carrinho
DELETE http://127.0.0.1:8000/carrinhos/1/2/1 HTTP/1.1
content-type: application/json


###################################################
#### Rota para remover carrinho associado a usuario
DELETE http://127.0.0.1:8000/carrinhos/1 HTTP/1.1
content-type: application/json



###################################################
#### Rota para remover endereco associado a usuario
DELETE http://127.0.0.1:8000/usuarios/1/2 HTTP/1.1
content-type: application/json


